/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package samplehtml;

/**
 *
 * @author Quang Trung
 */
public class SampleData {

    public static final String test1 = "<html><head></head><body><div><div class=\"email-print\">\n"
            + "                	<span class=\"spanTime\">Thứ sáu, 15/11/2013 16:04 GMT+7</span>\n"
            + "                    <div id=\"top-social\" class=\"rightEP\">\n"
            + "                        \n"
            + "                        <div class=\"fl\">\n"
            + "                            \n"
            + "                            	<img border=\"0\" src=\"http://st.f1.vnecdn.net/i/v120/icons/email.gif\">\n"
            + "                        </div>\n"
            + "                        <div class=\"fl\">\n"
            + "                            <a href=\"http://vnexpress.net/detail/print?id=2910832&amp;page=1\" target=\"_blank\">\n"
            + "                            	<img border=\"0\" src=\"http://st.f1.vnecdn.net/i/v120/icons/print.gif\"></a>\n"
            + "                        </div>\n"
            + "                        \n"
            + "                    </div>\n"
            + "                    </div>\n"
            + "                <div class=\"fck_detail\"><p class=\"Normal\">\n"
            + "	Khoảng 6h30 sáng nay, tàu SE7 đi từ Huế vào TP HCM trên đường sắt Bắc - Nam. Khi tàu đến địa bàn thôn Hảo Sơn, xã Hòa Xuân Nam, huyện Đông Hòa, tỉnh Phú Yên, một tảng đá nặng hàng tấn bất ngờ rơi từ sườn núi Đèo Cả xuống&nbsp;nằm giữa đường ray.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Sự cố bất ngờ này khiến tàu không dừng kịp. Đầu máy của đoàn tàu nặng hơn 8 tấn đâm vào đá, trật bánh khỏi đường ray. Rất may toàn bộ hành khách, lái tàu, nhân viên phục vụ <span>đều an toàn, chỉ bị chấn động hoảng hốt.</span></p>\n"
            + "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"tau-6670-1384505344.jpg\" src=\"http://m.f29.img.vnecdn.net/2013/11/15/tau-6670-1384505344.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Normal\">\n"
            + "					Nơi tàu SE7 gặp nạn. Ảnh: <em>Chí Phan</em></p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Sau khi xảy ra sự cố, Xí nghiệp Đường sắt Phú Khánh đã đưa tàu cứu hộ từ Nha Trang ra tiếp cận, nỗ lực giải phóng hiện trường. Tuy nhiên, đến trưa cùng ngày, tảng đá khủng mới được đưa đi. Giao thông đường sắt đã bị ách tắc nhiều giờ.&nbsp;<span>Hàng nghìn hành khách trên những chuyến tàu khác phải chờ đợi tại các ga hai bên Đèo Cả thuộc địa phận tỉnh Khánh Hòa và Phú Yên. Hiện lực lượng đang khẩn trương khắc phục sự cố, dự kiến sẽ thông chuyến chạy tàu vào chiều nay.</span></p>\n"
            + "<p class=\"Normal\">\n"
            + "	“Khi qua đèo, tàu SE7 chỉ chạy với vận tốc khoảng 30 km/h nên gặp sự cố chỉ trật bánh. Nếu chạy với vận tốc lớn hơn thì hậu quả thật khó lường vì gần sát đường sắt là vực biển\", ông Nguyễn Văn Long, Giám đốc Trung tâm ứng phó sự cố thiên tai và cứu nạn đường sắt khu vực 3, cho biết.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Từ đêm 14 đến sáng 15/11, trên địa bàn tỉnh Phú Yên có mưa lớn trên diện rộng, gây ngập lụt, sạt lở nhiều nơi. Vào mùa này, khu vực Đèo Cả thường xuyên xảy ra hiện tượng sạt lở đất, đá xuống đường sắt và quốc lộ 1, gây nguy hiểm, ách tắc giao thông.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	<strong>&nbsp;Chí Phan</strong></p></div>\n"
            + "                   \n"
            + "             </div></body></html>";
    public static final String test2 = "<html><head></head><body><div><div class=\"email-print\">\n"
            + "                	<span class=\"spanTime\">Thứ sáu, 15/11/2013 16:54 GMT+7</span>\n"
            + "                    <div id=\"top-social\" class=\"rightEP\">\n"
            + "                        \n"
            + "                        <div class=\"fl\">\n"
            + "                            \n"
            + "                            	<img border=\"0\" src=\"http://st.f1.vnecdn.net/i/v120/icons/email.gif\">\n"
            + "                        </div>\n"
            + "                        <div class=\"fl\">\n"
            + "                            <a href=\"http://vnexpress.net/detail/print?id=2910799&amp;page=1\" target=\"_blank\">\n"
            + "                            	<img border=\"0\" src=\"http://st.f1.vnecdn.net/i/v120/icons/print.gif\"></a>\n"
            + "                        </div>\n"
            + "                        \n"
            + "                    </div>\n"
            + "                    </div>\n"
            + "                <div class=\"fck_detail\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"0\" src=\"http://l.f29.img.vnexpress.net/2012/09/27/tausanbay1-147595-1368787963_500x0.jpg\" title=\"0\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Tàu sân bay Liêu Ninh của Hải quân&nbsp;Trung Quốc. Ảnh: <em>Xinhua</em></p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Bắc Kinh và Manila có tranh chấp tại các đảo trên biển nhưng nếu Philippines từ chối chấp nhận tàu chiến đến hỗ trợ thì \"chỉ thể hiện sự hẹp hòi của Philippines chứ Trung Quốc không thiệt gì cả\", tờ <em>Global Times</em>, phụ san của báo đảng Trung Quốc, viết trong một bài xã luận hôm nay.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	\"Chúng ta tin rằng Trung Quốc cũng sẽ cử các tàu chiến tới Philippines\", báo này viết, và nhấn mạnh rằng việc điều động tàu đi cứu trợ sẽ thể hiện thiện ý.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Quan hệ giữa Trung Quốc và Philippines căng thẳng vì tranh chấp lãnh thổ trong khu vực Biển Đông. Trung Quốc tuyên bố chủ quyền đối với gần như toàn bộ Biển Đông trong khi Manila nói tàu Trung Quốc chiếm đóng bãi cạn Scarborough/ Hoàng Nham mà Philippines tuyên bố chủ quyền. Theo <em>AFP</em>, Philippines sẽ phải đặt ra câu hỏi có nên chào đón sự xuất hiện của Hải quân Trung Quốc trong khu vực hay không.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Trong khi các tàu, máy bay và quân nhân của Mỹ và Nhật đang hối hả cứu trợ cho Philippines sau bão Haiyan, báo của Trung Quốc bình luận rằng nỗ lực của hai nước này là một phần của chiến lược xoay trục sang châu Á của Washington và có thể bao gồm \"ý định ẩn giấu đằng sau mục đích viện trợ nhân đạo\".</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Trên thực địa, một đội 8 chiếc tàu của Mỹ, do tàu sân bay USS George Washington dẫn đầu, hôm qua đã đến Philippines, mang theo các thiết bị và nhu yếu phẩm để hỗ trợ cho hàng nghìn người mất nhà cửa và đói khát sau cơn bão mạnh nhất trong lịch sử. Các máy bay vận tải của Mỹ đã chở 50 nghìn tấn hàng chuyển tới miền trung Philippines, nơi hứng chịu hậu quả nặng nề nhất do bão.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Nhật Bản cũng đang tăng gói viện trợ cho Philippines lên gấp ba lần, lên 30 triệu USD, và dự kiến sẽ cử 1.000 binh sĩ tới vùng thiệt hại của Philippines. Đây là đội cứu trợ lớn nhất của lực lượng Phòng vệ Nhật Bản được cử ra hoạt động ở nước ngoài.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Bài xã luận của <em>Global Times</em> xuất hiện một ngày sau khi Trung Quốc quyết định nâng mức viện trợ cho Philippines vì siêu bão Haiyan lên 1,6 triệu USD, chủ yếu bao gồm các lều trại và chăn màn cho các nạn nhân vùng bão. Trước đó, Trung Quốc nhận được những chỉ trích vì mức ủng hộ khiêm tốn 100.000 USD.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Tờ báo của đảng cho rằng trong quá khứ Trung Quốc thận trọng về việc gửi binh sĩ ra nước ngoài vì \"thiếu năng lực, thiếu kinh nghiệm và nhiều mối lo ngại khác\". Tuy nhiên, ngày nay \"quân đội Trung Quốc cần phải dần đảm nhiệm vai trò mạnh mẽ hơn cho phù hợp với chính sách ngoại giao của mình\".</p>\n"
            + "<p class=\"Normal\">\n"
            + "	<strong>Vũ Hà</strong></p></div>\n"
            + "                </div></body></html>";
    public static final String test3 = "<html><head></head><body><div>\n"
            + "                                <p class=\"short_intro txt_666\">\n"
            + "                                    Lãi trước thuế quý III giảm hơn 6 lần so với cùng kỳ, nợ xấu đến 30/9 tăng lên 5,9% nhưng ngân hàng vẫn điều chỉnh thu nhập cho một số vị trí khiến quỹ lương tăng.                                </p>\n"
            + "                                                                <div class=\"fck_detail\">\n"
            + "                                    <table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"Techcombank-giaodich-3686-1384506452.jpg\" src=\"http://m.f25.img.vnecdn.net/2013/11/15/Techcombank-giaodich-3686-1384506452.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Nợ xấu của Techcombank sau 9 tháng là 5,9%. Ảnh: <em>TCB.</em></p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Ngân hàng Kỹ Thương Việt Nam (Techcombank) vừa công bố báo cáo tài chính hợp nhất quý III. Mảng vàng, ngoại tệ lỗ 118 tỷ đồng trong khi các mảng khác đều có lãi. Trước trích lập dự phòng, Techcombank lãi hơn 410 tỷ đồng nhưng do nợ xấu trong quý tăng khiến chi phí dự phòng rủi ro lớn, kéo lợi nhuận trước thuế xuống 97 tỷ - giảm hơn 6 lần so với cùng kỳ năm ngoái.&nbsp;</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Lũy kế 9 tháng, Techcombank lãi trước thuế 750 tỷ, giảm 66% so với cùng kỳ năm 2012. Tín dụng của ngân hàng sau ba quý chỉ tăng trưởng 2,4%. Chi phí dự phòng rủi ro xử lý nợ xấu gấp 3 lần năm ngoái. Nợ xấu đến 30/9 tăng lên 5,9% (quý II nợ xấu chiểm 5,2% dư nợ). Theo thuyết minh báo cáo tài chính, Techcombank còn khoảng hơn 4.100 tỷ đồng nợ xấu.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Lý giải với <em>VnExpress.net</em> về nguyên nhân nợ xấu không giảm mà tăng mạnh, ông Đỗ Tuấn Anh - quyền Tổng giám đốc Techcombank - cho rằng những giải pháp xử lý nợ tập trung của ngân hàng \"cần thời gian để chứng tỏ tính hiệu quả\". \"Như các ngân hàng khác, khách hàng của Techcombank cũng chịu nhiều tác động của suy thoái, nhiều trong số đó dù cầm cự được một thời gian nhưng đã bắt đầu gặp khó khăn nên khó trả nợ đúng hạn cho ngân hàng\", ông Tuấn Anh giải thích.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Dù lợi nhuận giảm, nợ xấu lên 5,9%, quỹ lương của Techcombank trong quý vẫn tăng so với cùng kỳ. Thu nhập bình quân của mỗi nhân viên Techcombank trong năm nay là hơn 15 triệu đồng trong khi năm 2012 là 12 triệu. Về vấn đề này, CEO của ngân hàng giải thích, quỹ lương tăng do trong quý III có điều chỉnh lương cho những nhân viên có thành tích tốt và đóng góp đáng kể.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Quý III, Techcombank tuyển thêm 535 nhân viên mới, lượng tuyển mới nhiều hơn so với hai quý đầu năm. Lãnh đạo Techcombank cho biết, quý IV dự kiến sẽ tuyển dụng, đào tạo mới gần 300 nhân viên ở nhiều vị trí.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Lợi nhuận của ngân hàng quý III giảm một phần do chi phí hoạt động tăng 42%. Trả lời <em>VnExpress</em>, đại diện Techcombank giải thích do trong quý, ngân hàng mạnh tay đầu tư phát triển nhân sự, mở rộng mạng lưới, chuyển trụ sở tại TP HCM.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	<strong>Thanh Thanh Lan</strong></p>                                    </div>\n"
            + "                                                                \n"
            + "                                                    </div></body></html>";
    public static final String test4 = "<html><head></head><body><div>\n"
            + "                        <p class=\"short_intro\">Lời giới thiệu của FIFA về các đề cử cho phần thưởng Quả Bóng Vàng 2013 được xem là bằng chứng về sự phân biệt đối xử giữa ba ứng viên nặng ký nhất.</p>\n"
            + "\n"
            + "                                                    <div class=\"fck_detail\"><p class=\"Normal\">\n"
            + "	\"2013 là một năm bội thu bàn thắng của Cristiano Ronaldo. Ngôi sao người Bồ Đào Nha có 34 bàn ở La Liga mùa 2012-2013, một kỳ tích chỉ kém 46 bàn của Lionel Messi, và ghi thêm rất nhiều bàn ở Cup châu Âu cũng như ĐTQG. Luôn đạt phong độ cao ở Real và tuyển Bồ Đào Nha, chân sút từng đoạt giải Cầu thủ hay nhất thế giới năm 2008 đang trở thành biểu tượng với Los Merengues (biệt danh của Real). Và không có gì ngạc nhiên khi anh gia hạn hợp đồng đến 2018 và nói rằng anh xem xét kết thúc sự nghiệp trong màu áo CLB\", FIFA viết về Ronaldo.</p>\n"
            + "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"ronaldo-vs-messi-2013-h1n-net-5649-13845\" src=\"http://m.f1.img.vnecdn.net/2013/11/15/ronaldo-vs-messi-2013-h1n-net-5649-1384503454.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Xét về số bàn thắng, Ronaldo rõ ràng thua thiệt khi so sánh với Messi.</p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Ngoài chuyện đưa ra so sánh, làm rõ khác biệt giữa 34 bàn của Ronaldo với 46 bàn của Messi, FIFA dường như còn ngầm nhắc tới vụ ngôi sao người Bồ Đào Nha yêu sách buộc Real phải tăng lương cho anh lên 17 triệu euro mỗi năm - mức cao nhất thế giới bóng đá hiện tại.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Hồ sơ của Messi thì được viết: \"Sau khi đoạt bốn Quả Bóng Vàng liên tiếp, ngôi sao của Barca không hề có dấu hiệu dễ dãi, anh dẫn đầu danh sách làm bàn của La Liga trong mùa giải 2012-2013 mà đội nhà vô địch. Messi cũng rất ấn tượng ở cấp đội đội tuyển, khi có số bàn thắng cao thứ hai hành trình vòng loại World Cup 2014 khu vực Nam Mỹ. Trong khi chờ đợi vòng chung kết World Cup thứ ba trong sự nghiệp vào năm tới, ảo thuật gia tấn công 26 tuổi này đang tiến rất nhanh đến một kỷ lục nữa khi anh cố gắng trở thành cầu thủ ghi bàn nhiều nhất trong lịch sử Champions League\".</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Những dòng này hầu như không đả động đến một chi tiết có thể làm ảnh hưởng đến số phiếu bình chọn cho Messi - thất bại chung cuộc 0-7 của anh và Barca ở bán kết Champions League. Messi không đá trận lượt về vì chấn thương, nhưng anh đá cả trận lượt đi mà không thể giúp Barca tránh thảm bại 0-4.</p>\n"
            + "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"CL-5228-1384503454.jpg\" src=\"http://m.f1.img.vnecdn.net/2013/11/15/CL-5228-1384503454.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Ác mộng của Messi ở Champions League mùa trước không hề được FIFA đề cập.</p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Với trường hợp Ribery, FIFA tỏ ra tôn trọng sự thật hơn cả, đúng theo thực tế không tì vết của ngôi sao người Pháp trong năm qua: \"Sự căng thẳng nhen nhóm trở lại với Franck Ribery trong năm 2012, khi Bayern Munich về nhì ở Bundesliga, Cup Quốc Gia và UEFA Champions League. Nhưng cầu thủ đá cánh lợi hại người Pháp này không phải chờ quá lâu để tiêu hóa những kỷ niệm buồn. Chơi bóng với trình độ khác hẳn sau những kết quả thất vọng trước đó, anh giúp đội nhà vô địch ở cả ba giải đấu trong năm 2013, rồi bổ sung thêm vào bộ sưu tập một chiếc Siêu Cup châu Âu. Hơn nữa, anh cũng tỏa sáng trong màu áo tuyển Pháp gần đây, trở thành một cầu thủ có đóng góp quan trọng và quyết định hơn trên đấu trường quốc tế\".</p>\n"
            + "<p class=\"Normal\">\n"
            + "	FIFA cũng đề cập việc Ribery đã chiến thắng Messi và Ronaldo ở cuộc bình chọn quan trọng của UEFA hè vừa qua.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Ronaldo, Messi và Ribery chính là ba cái tên được đánh giá cao nhất trong danh sách 23 đề cử cho Quả Bóng Vàng 2013 - phần thưởng cá nhân cao quý nhất bóng đá trong năm - mà FIFA công bố hôm 29/10.</p>\n"
            + "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"Ribery-2604-1384503455.jpg\" src=\"http://m.f1.img.vnecdn.net/2013/11/15/Ribery-2604-1384503455.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Trước cuộc đua tranh Quả Bóng Vàng,&nbsp;Ribery đã thắng Messi và Ronaldo ở giải Cầu thủ hay nhất châu Âu 2013 của UEFA.</p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Đầu tháng 12, FIFA sẽ rút gọn danh sách ứng viên Bóng vàng xuống còn 3 người. Phải tới ngày 13/1/2014, giải thưởng mới được công bố bên cạnh các hạng mục HLV hay nhất, Bàn thắng đẹp nhất và Đội hình tiêu biểu.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Nói về Messi, Chủ tịch FIFA Sepp Blatter hôm 28/10 phát biểu:&nbsp;<span>\"Messi là một chàng trai tốt mà bất cứ ông bố, bà mẹ nào cũng muốn có. Cậu ấy rất nhanh, chơi bóng như nhảy múa. Tuy nhiên, điều khiến Messi nổi tiếng không phải là các bàn thắng mà là phẩm chất tốt đẹp cậu ấy thể hiện\".</span></p>\n"
            + "<p class=\"Normal\">\n"
            + "	Về Ronaldo, Blatter cũng bày tỏ sự khâm phục trước tài đá bóng. Nhưng ông không quên nhắc nhở cá tính mang hơi hướng trình diễn của cầu thủ này. \"Ronaldo lúc nào cũng như một nhà chỉ huy trên sân cỏ\", Blatter vừa nói vừa nhại lại động tác của CR7. \"Cậu ta cống hiến mọi thứ cho bóng đá, thậm chí không tiếc chi cả đống tiền cho thợ làm tóc trước khi ra sân\".</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Blatter sau đó phải xin lỗi Real Madrid và cá nhân Ronaldo vì những phát ngôn này.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	<strong>Phương Minh</strong></p></div>\n"
            + "                        \n"
            + "                                            </div></body></html>";
    public static final String test5 = "<html><head></head><body><div><div class=\"fck_detail\"><table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"Chiếc Cayenne Turbo mới bị bắt giữ hôm 14/11. Ảnh: An Nhơn\" src=\"http://m.f29.img.vnecdn.net/2013/11/15/sieu-xe-1-2832-1384500332.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Chiếc Cayenne Turbo mới bị bắt giữ hôm 14/11. Ảnh: <em>An Nhơn</em></p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Công an quận 7 (TP HCM) hôm 14/11 tiếp tục tạm giữ&nbsp; ôtô Cayenne Turbo đậu tại khu Phú Mỹ Hưng vì có dấu hiệu sử dụng bảng số giả, nâng tổng số các xe sang bị đơn vị bắt giữ tại khu đô thị hiện đại nhất nước lên con số 13. Trong đó có 3 siêu xe&nbsp;Bentley, 1 Lexus, 1 Porsche, 1 Mercedes-Benz và 1 Hummer mang biển số giả.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Trao đổi với <em>VnExpress</em> ngày 15/11, thượng tá Đoàn Văn Nam, Đội trưởng Cảnh sát kinh tế Công an quận 7, TP HCM cho biết, 13 xe sang vừa bị bắt giữ tại khu đô thị Phú Mỹ Hưng trong thời gian qua đều mang biển số ngoại giao nhưng không có giấy tờ hoặc biển số giả. Qua xác minh, những ôtô này được các nhân viên đại sứ quán nước ngoài nhập vào Việt Nam sử dụng khoảng 3 năm. Khi hết nhiệm kỳ, họ không đưa về nước mà bán lại cho người có nhu cầu.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Những ôtô hạng sang này khi được các đại sứ quán nhập vào Việt Nam được miễn thuế, có tờ khai hải quan. Theo quy định, người mua phải làm thủ tục sang tên, đóng thuế thì mới được phép lưu hành. Nhưng khi một số \"đại gia\" Việt Nam mua, số tiền đóng thuế cao, họ muốn trốn thuế nên đã làm giấy tờ, biển số giả để chạy.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Vị đội trưởng cũng cho biết thêm, để làm rõ được nguồn gốc của những chiếc xe mang biển số ngoại giao cần thời gian rất lâu. Công an quận 7 phải gửi công văn đến Cục Cảnh sát giao thông, Cục Lễ tân Bộ ngoại giao, sau đó sẽ phiên dịch và gửi đến văn phòng đại sự quán nơi đăng ký phương tiện để xác minh và chờ công văn trả lời.</p>\n"
            + "<table border=\"0\" cellpadding=\"3\" cellspacing=\"0\" class=\"tplCaption\" width=\"1\"><tbody><tr><td>\n"
            + "				<img alt=\"Công an quận 7 vẫn đang tạm giữ 7 xe chờ xác minh nguồn gốc. Ảnh: An Nhơn\" src=\"http://m.f29.img.vnecdn.net/2013/11/15/sieu-xe-6380-1384500332.jpg\"></td>\n"
            + "		</tr><tr><td>\n"
            + "				<p class=\"Image\">\n"
            + "					Công an quận 7 vẫn đang tạm giữ 7 xe chờ xác minh nguồn gốc. Ảnh: <em>An Nhơn</em></p>\n"
            + "			</td>\n"
            + "		</tr></tbody></table><p class=\"Normal\">\n"
            + "	Theo thượng tá Nam, trong số 13 xe tạm giữ có 6 chiếc là xe mang biển ngoại giao, đã chuyển cho Cảnh sát giao thông xử phạt hành chính. Nếu chủ xe có giấy tờ gốc là xe được nhập vào Việt Nam theo diện ngoại giao, tức là không cần phải đóng thuế. Khi muốn nhận lại xe bị tạm giữ, chủ phương tiện sẽ phải đóng thuế nhập khẩu và thuế trước bạ mới được lấy xe ra.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	3 trong 7 chiếc còn lại được xác định là dùng giấy tờ và biển số giả để lưu thông đã được Công an quận 7 khởi tố, điều tra về hành vi Sử dụng giấy tờ giả. Trong số này có 1 xe Bentley, 1 chiếc Mercedes-Benz cùng mang biển TP HCM, 1 xe Bentley màu trắng 4 cửa mang biển Hà Nội. Trong đó, chiếc Bentley từng bị cảnh sát giao thông xử phạt vì chạy quá tốc độ.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	\"Giấy tờ của những chiếc xe này được làm giả rất tinh vi nên khi Cảnh sát giao thông kiểm tra, nhìn bằng mắt thường rất khó phát hiện. Chỉ bằng các biện pháp nghiệp vụ, cơ quan điều tra mới xác minh được nguồn gốc và lật tẩy đó là xe xài giấy tờ và biển số giả\", thượng tá Nam nói.</p>\n"
            + "<p class=\"Normal\">\n"
            + "	Đối với 4 siêu xe còn lại, theo thượng tá Nam, đó là những chiếc xe chưa xác minh được nguồn gốc nên chưa tìm ra chủ sở hữu. Còn việc những người này không chủ động đến làm việc với cơ quan điều tra, có thể do họ dùng giấy tờ, biển số giả nên sợ bị xử lý nặng.</p>\n"
            + "<p>\n"
            + "	<strong>An Nhơn</strong></p></div>\n"
            + "                   \n"
            + "             </div></body></html>";
}
